- name: update arm boards
  hosts: armBoards
  become: true
  remote_user: branson
  vars_files: 
    /Users/ericbranson/Documents/Cluster/armBoards/vault_vars.yaml
  vars:
    branson_password: "{{ lookup('community.general.onepassword',
      'music pi',
      field='password',
      vault='Ansible',
      service_account_token=auth_token)
      }}"
  tasks:
    - name: Update apt
      ansible.builtin.apt:
        update_cache: true
        upgrade: true
        cache_valid_time: 3600
    - name: Syncronize scripts folder
      ansible.builtin.copy:
        src: /Users/ericbranson/Documents/Cluster/armBoards/scripts
        dest: /home/branson/
        mode: '755'
    - name: Check if reboot required
      ansible.builtin.stat:
        path: /var/run/reboot-required
      register: reboot_required_file
    - name: Reboot if required
      ansible.builtin.reboot:
        connect_timeout: 5
        reboot_timeout: 10
        post_reboot_delay: 30
        test_command: uptime
      when: reboot_required_file.stat.exists == true
...