
- name: Apt update
  ansible.builtin.apt:
    update_cache: true
    upgrade: true
- name: Check if reboot required
  ansible.builtin.stat:
    path: /var/run/reboot-required
  register: reboot_required
- name: Reboot if required
  ansible.builtin.reboot:
    connect_timeout: 5
    reboot_timeout: 600
    post_reboot_delay: 30
    test_command: uptime
  when: reboot_required.stat.exists
