---
- name: Initialize chromebox
  hosts: chromebox13.local
  become: true
  remote_user: branson
  become_method: sudo
  gather_facts: true # for initial run need to use bad "branson" password
  vars_files: 
    /Users/ericbranson/Documents/Cluster/vault_vars.yaml
  vars:
  collections:
  - onepassword.connect
  tasks:
    - name: Set hostname
      ansible.builtin.hostname:
        name: "{{ inventory_hostname }}"
    - name: init
      ansible.builtin.import_tasks:
        file: "/Users/ericbranson/Documents/Cluster/tasks/init.yaml"
    - name: Install OMZ
      ansible.builtin.import_tasks:
        file: "/Users/ericbranson/Documents/Cluster/tasks/installOMZ.yaml"
    
... 