---
- name: Init arm boards
  hosts: armBoards
  remote_user: branson
  become_method: sudo
  become: true
  vars_files: 
    /Users/ericbranson/Documents/Cluster/armBoards/vault_vars.yaml
  vars:
    ansible_become_password: "{{ branson_password }}"
    branson_password: "{{ lookup('community.general.onepassword',
      'music pi',
      field='password',
      vault='Ansible',
      service_account_token=auth_token)
      }}"
    ssh_key_path: "/home/branson/.ssh/{{ inventory_hostname }}_branson_id"
    ssh_key_pub: '{{ ssh_key_path }}.pub'
    blacklist: ['lo']
    devices: "{{ interfaces | map('extract', vars) | items2dict(key_name='device', value_name='address') }}"
  tasks:
    - name: Copy ssh-id from mac
      ansible.builtin.command:
        cmd: ssh-copy-id branson@{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}
      delegate_to: ericsMac
      delegate_facts: true
      connection: local
      become: true
      become_user: ericbranson
      vars:
        ansible_sudo_password: "{{ lookup('community.general.onepassword',
          'ericsMac',
          field='password',
          vault='Ansible',
          service_account_token=auth_token)
          }}"
    - name: Set defaults and install thru apts
      ansible.builtin.import_tasks:
        file: "../../tasks/init.yaml"
    - name: Install OMZ
      ansible.builtin.import_tasks:
        file: "../../../tasks/installOMZ.yaml"
    - name: Install wiringPi
      ansible.builtin.import_tasks:
        file: "../tasks/installWiringPi.yaml"

 
    - name: Copy over conf file
      ansible.builtin.copy:
        src: /Users/ericbranson/Documents/Cluster/armBoards/shairport-sync.conf
        dest: /etc/shairport-sync.conf
        mode: a=rw
      # vars:
      #   airplay_name: "{{ hostvars | regex('/[A-Z-_\&](?=[a-z0-9]+)|[A-Z-_\&]+(?![a-z0-9])/g') }}"

...
        