---
- name: Initialize vms
  hosts: all
  become: true
  remote_user: branson
  vars_files:
    ~/Documents/Cluster/Multipass/secrets/vault_vars.yaml
  vars:
    branson_password: "{{ lookup('community.general.onepassword',
      'chromeboxes',
      field='password',
      vault='Ansible',
      service_account_token=auth_token)
      }}"
  tasks:
    - name: Fix network start delay
      ansible.builtin.copy:
        src: ~/Documents/Linux/systemd-networkd-wait-online.service
        dest: /etc/systemd/system/network-online.target.wants/systemd-networkd-wait-online.service
        owner: root
        mode: u=rwx,g=rx
    - name: Set timezone
      community.general.timezone:
        name: America/Boise
    - name: Change password
      ansible.builtin.user:
        name: branson
        password: "{{ branson_password | password_hash('sha512') }}"
    - name: Install thru apt
      ansible.builtin.apt:
        update_cache: true
        upgrade: true
        name:
          - zsh
          - python3-dev
          - python3-pip
          - python3-setuptools
    - name: Install theFuck
      ansible.builtin.pip:
        name: thefuck
    - name: Change shell
      ansible.builtin.user:
        name: branson
        shell: /bin/zsh
    - name: Download install OMZ script
      ansible.builtin.uri:
        url: https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh
        dest: /home/branson/installOMZ.sh
        owner: branson
        mode: ug=rwx
      register: download_result
    - name: Install OMZ
      ansible.builtin.command:
        cmd: /home/branson/installOMZ.sh --unattended
        creates: /home/branson/installLog.txt
      when: download_result.failed is false or script_exists.state is file
    - name: Set Zsh Config
      ansible.builtin.copy:
        src: ~/Documents/Cluster/Multipass/configs/zshrc.conf
        dest: /home/branson/.zshrc
        owner: branson
        mode: ug=rw,
    - name: Auto remove
      ansible.builtin.apt:
        autoremove: true
    - name: Reboot
      ansible.builtin.reboot:
        connect_timeout: 5
        reboot_timeout: 600
        post_reboot_delay: 30
        test_command: uptime
