---
- name: Initialize proxy hosts
  hosts: proxyCluster
  remote_user: branson
  become: true
  vars_files: 
    /Users/ericbranson/Documents/Cluster/secrets/vault_vars.yaml
  vars:

  tasks:
    - name: Look for network interfaces
      ansible.builtin.setup:
        gather_subset:
          - network
      register: network_facts
    - name: Add dummy network interfaces
      become: true
      ansible.builtin.command:
        cmd: ip link add {{ item }} type dummy
      loop:
        - Den01
        - Dwl01
      when: item not in network_facts.ansible_facts.ansible_interfaces
      register: dummy_networks
    - name: Set dummy interfaces up
      ansible.builtin.command:
        cmd: ip link set dev {{ item }} up
      loop: 
        - Den01
        - Dwl01
      when: item in dummy_networks
    - name: Save facts
      ansible.builtin.copy:
        content: "{{ ansible_facts | to_nice_yaml }}"
        dest: /Users/ericbranson/Documents/Cluster/Multipass/facts.yaml
      when: inventory_hostname == "iras01"
      delegate_to: localhost
      delegate_facts: true
      become_user: ericbranson
      become: true
      vars:
        ansible_become_pass: "{{ lookup( 'community.general.onepassword', 'macMini', field='password', vault='Ansible', service_account_token=auth_token) }}"
    - name: Install thru apt
      ansible.builtin.apt:
        update_cache: true
        name: "{{ item }}"
      loop:
        - keepalived
        - haproxy
        - inadyn
    - name: Install certbot
      community.general.snap:
        name: certbot
        classic: true
    - name: Setup the symbolic link
      ansible.builtin.file:
        src: /snap/bin/certbot
        dest: /usr/bin/certbot
        state: link
    - name: Acknowledge warning
      ansible.builtin.command: snap set certbot trust-plugin-with-root=ok
      register: output
    - name: Install certbot cloudflare plugin
      community.general.snap:
        name: certbot-dns-cloudflare
    - name: Setup certbot user
      ansible.builtin.user:
        name: certbot
        home: /opt/certbot
        state: present
    - name: Certbot sudoer
      community.general.sudoers:
        name: certbot
        user: certbot
        nopassword: true
        commands:
          - /bin/systemctl restart haproxy
    - name: Add haproxy to certbot group
      ansible.builtin.user:
        name: haproxy
        groups: certbot
        append: true
    - name: Add branson to certbot group
      ansible.builtin.user:
        name: branson
        groups: certbot
        append: true
    - name: Add certbot opt folders
      ansible.builtin.file:
        state: directory
        path: "/opt/certbot/{{ item }}"
        owner: certbot
        mode: ug=rx
      loop:
        - config
        - logs
    - name: Add certbot etc folders
      ansible.builtin.file:
        state: directory
        path: /etc/certbot/renewal
        owner: certbot
        mode: ug=rx
    - name: Configure certbot
      ansible.builtin.template:
        src: ~/Documents/Cluster/Multipass/configs/certbot-initial.conf
        dest: /opt/certbot/config/certbot.conf
        owner: certbot
        mode: ug=rx
    - name: Gather facts about network interfaces
      ansible.builtin.setup:
        gather_subset: network
      register: interface_facts
    - name: Create keepalived conf file
      ansible.builtin.template:
        src: /Users/ericbranson/Documents/Cluster/Multipass/configs/keepalived_proxy.conf.j2
        dest: /etc/keepalived/keepalived.conf
    - name: Add haproxy folders
      ansible.builtin.file:
        state: directory
        path: /etc/haproxy/
        mode: ug=rx
    - name: Print vars
      ansible.builtin.debug:
        msg: "{{ k3sControl }}"
    - name: Configure haproxy
      ansible.builtin.template:
        src: ~/Documents/Cluster/Multipass/configs/haproxy.conf
        dest: /etc/haproxy/haproxy.cnf
        mode: ug=rx
    - name: Generate DH params field
      community.crypto.openssl_dhparam:
        path: /opt/certbot/dhparams.pem
        owner: certbot
        group: certbot
        mode: u=rwx, go=r
        size: 4096
    - name: Configure inadyn
      ansible.builtin.copy:
        src: ~/Documents/Cluster/Multipass/configs/inadyn.conf
        dest: /etc/inadyn.conf
        mode: ug=rx
    - name: Enable everything
      ansible.builtin.systemd_service:
        name: "{{ item }}"
        enabled: true
        state: reloaded
      loop:
        - keepalived
        - haproxy
        - inadyn
    - name: Reboot
      ansible.builtin.reboot:
        connect_timeout: 5
        reboot_timeout: 600
        post_reboot_delay: 30
        test_command: uptime
...
