---
- name: Initialize proxy hosts
  hosts: proxyCluster
  remote_user: branson
  become: true
  vars_files:
    ~/Documents/Cluster/Multipass/secrets/vault_vars.yaml
  vars:
    api_token: "{{ lookup('community.general.onepassword',
        'Cloudflare DNS zone key',
        field='credential',
        vault='Ansible',
        service_account_token=auth_token)
        }}"
  tasks:
    - name: Install keepalived
      ansible.builtin.apt:
        update_cache: true
        name: keepalived
    - name: Install haproxy
      ansible.builtin.apt:
        name: haproxy
    - name: Install inadyn
      ansible.builtin.apt:
        name: inadyn
    - name: Install certbot
      community.general.snap:
        name: certbot
        classic: true
    - name: Setup the symbolic link
      ansible.builtin.file:
        src: /snap/bin/certbot
        dest: /usr/bin/certbot
        state: link
    - name: Acknowledge warning
      ansible.builtin.command: snap set certbot trust-plugin-with-root=ok
      register: output
      changed_when: output.msg.changed is true
      failed_when: output.msg.failed is true
    - name: Install certbot cloudflare plugin
      community.general.snap:
        name: certbot-dns-cloudflare
    - name: Setup certbot user
      ansible.builtin.user:
        name: certbot
        home: /opt/certbot
    - name: Add haproxy to certbot group
      ansible.builtin.user:
        name: haproxy
        groups: certbot
        append: true
    - name: Add branson to certbot group
      ansible.builtin.user:
        name: branson
        groups: certbot
        append: true
    - name: Add certbot opt folders
      ansible.builtin.file:
        state: directory
        path: /opt/certbot
        owner: certbot
        mode: ug=rx
    - name: Add certbot etc folders
      ansible.builtin.file:
        state: directory
        path: /etc/certbot/renewal
        owner: certbot
        mode: ug=rx
    - name: Configure certbot
      ansible.builtin.copy:
        src: ~/Documents/Cluster/Multipass/configs/certbot.conf
        dest: /etc/certbot/renewal/certbot.conf
        owner: certbot
        mode: ug=rx
    - name: Copy over cloudflare credentials
      ansible.builtin.template:
        src: ~/Documents/Cluster/Multipass/configs/cloudflareAPI.ini
        dest: /etc/certbot/cloudflareAPI.ini
        owner: certbot
        mode: ug=rx
    - name: Configure keepalived
      ansible.builtin.copy:
        src: ~/Documents/Cluster/Multipass/configs/keepalived.conf
        dest: /etc/keepalived/keepalived.conf
        mode: ug=rx
    - name: Add haproxy folders
      ansible.builtin.file:
        state: directory
        path: /etc/haproxy/
        mode: ug=rx
    - name: Configure haproxy
      ansible.builtin.copy:
        src: ~/Documents/Cluster/Multipass/configs/haproxy.cnf
        dest: /etc/haproxy/haproxy.cnf
        mode: ug=rx
    - name: Enable keepalived
      ansible.builtin.systemd_service:
        name: keepalived
        enabled: true
        state: reloaded
    - name: Enable haproxy
      ansible.builtin.systemd_service:
        name: haproxy
        enabled: true
        state: reloaded
    - name: Configure inadyn
      ansible.builtin.copy:
        src: ~/Documents/Cluster/Multipass/configs/inadyn.conf
        dest: /etc/inadyn.conf
        mode: ug=rx
    - name: Enable inadyn
      ansible.builtin.systemd_service:
        name: inadyn
        enabled: true
        state: reloaded
    - name: Reboot
      ansible.builtin.reboot:
        connect_timeout: 5
        reboot_timeout: 600
        post_reboot_delay: 30
        test_command: uptime
