- name: Initialize proxy hosts
  hosts: proxyCluster
  remote_user: branson
  become: true
  vars_files:
    ~/Documents/Cluster/Multipass/secrets/vault_vars.yaml
  vars:
    api_token: "{{ lookup('community.general.onepassword',
        'Cloudflare DNS zone key',
        field='credential',
        vault='Ansible',
        service_account_token=auth_token)
        }}"
  tasks:
    - name: Configure certbot
      ansible.builtin.copy:
        src: ~/Documents/Cluster/Multipass/configs/certbot.conf
        dest: /etc/letsencrypt/renewal/certbot.conf
        mode: ug=rx
    - name: Copy over cloudflare credentials
      ansible.builtin.template:
        src: ~/Documents/Cluster/Multipass/configs/cloudflareAPI.ini
        dest: /etc/certbot/cloudflareAPI.ini
        mode: ug=rx
    - name: Configure keepalived
      ansible.builtin.copy:
        src: ~/Documents/Cluster/Multipass/configs/keepalived.conf
        dest: /etc/keepalived/keepalived.conf
        mode: ug=rx
    - name: Configure haproxy
      ansible.builtin.copy:
        src: ~/Documents/Cluster/Multipass/configs/haproxy.cnf
        dest: /etc/haproxy/haproxy.cnf
        mode: ug=rx
    - name: Ru
      system