- name: Initialize audio players
  hosts: audio_players
  remote_user: branson
  become: true
  become_method: sudo
  vars_files:
    - /Users/ericbranson/Documents/Cluster/vault_vars.yaml
    - ../vars/vars.yaml
  tasks:
  - name: Clone nqptp
    ansible.builtin.git:
      repo: https://github.com/mikebrady/nqptp.git
      clone: true
      dest: /home/branson/nqptp
  - name: Nqptp autoreconf 
    ansible.builtin.command:
      chdir: /home/branson/nqptp
      cmd: '{{ item }}'
    loop:
      - autoreconf -fi
      - ./configure --with-systemd-startup
      - make
  - name: Install nqptp
    ansible.builtin.command:
      cmd: make install
      chdir: /home/branson/nqptp
    become: true
  - name: Enable nqptp
    ansible.builtin.systemd_service:
      name: nqptp
      state: restarted
      enabled: true
  - name: Clone shairport-sync
    ansible.builtin.git:
      repo: https://github.com/mikebrady/shairport-sync.git
      clone: true
      dest: /home/branson/shairport-sync
  - name: Shairport-sync autoreconf
    ansible.builtin.command:
      chdir: /home/branson/shairport-sync
      cmd: '{{ item }}'
    loop:
      - autoreconf -fi
      - ./configure --sysconfdir=/etc --with-alsa --with-soxr --with-avahi --with-ssl=openssl --with-systemd --with-airplay-2
      - make
  - name: Install shairport-sync
    ansible.builtin.command:
      chdir: /home/branson/shairport-sync
      cmd: make install
    become: true
  - name: Make scripts dir
    ansible.builtin.file:
      state: directory
      path: /home/branson/scripts
      owner: branson
      mode: "ug=rww,a=r"
  - name: Make log file
    ansible.builtin.file:
      state: touch
      path: /home/branson/shairport-sync/log.log
      owner: branson
      mode: "ug=rw,a=r"
  - name: Template out shairport-sync.conf
    ansible.builtin.template:
      src: ../templates/shairport-sync.conf
      dest: /etc/shairport-sync.conf
      mode: "ug=rw,a=r"
    vars:
      airplay_name: "{{ hostvars | regex('/[A-Z-_\\&](?=[a-z0-9]+)|[A-Z-_\\&]+(?![a-z0-9])/g') }}"
  - name: Enable shairport-sync
    ansible.builtin.systemd_service:
      name: shairport-sync
      state: restarted
      enabled: true