- name: Initialize VMs
  hosts: vms
  become: true
  remote_user: branson
  vars:
    auth_token: onePassAuthToken.yaml
    user_password: lookup('onepassword', 'chromebox', subdomain='Ansible', secret_key={{ auth_token }})
  tasks:
    - name: Fix network start delay
      ansible.builtin.copy:
        src: ~/Documents/Linux/systemd-networkd-wait-online.service
        dest: /etc/systemd/system/network-online.target.wants/systemd-networkd-wait-online.service
        owner: root
        mode: u=rwx,g=rx
    - name: Set timezone
      community.general.timezone:
        name: America/Boise
    - name: Change password
      ansible.builtin.user:
        name: branson
        password: "{{ user_password | password_hash('sha512') }}"
    - name: Apt update
      ansible.builtin.apt:
        update_cache: true
        upgrade: true
    - name: Check for reboot
      register: reboot_required_file
      ansible.builtin.stat:
        path: /var/run/reboot-required
        get_checksum: false
    - name: Auto remove
      ansible.builtin.apt:
        autoremove: true
    - name: Reboot
      ansible.builtin.reboot:
        connect_timeout: 5
        reboot_timeout: 100
        post_reboot_delay: 30
        test_command: uptime
