name: Initialize chromeboxes
hosts: all
remote_user: branson
become: true

tasks:
  - name: fix network start delay
    anible.builtin.copy:
      src: ~/Documents/Linux/systemd-networkd-wait-online.service
      dest: /etc/systemd/system/network-online.target.wants/systemd-networkd-wait-online.service
      owner: root
  - name: Set timezone
    community.general.timezone:
      name: America/Boise
  - name: Change password
    ansible.builtin.user:
      name: branson
      password: "{{ lookup('community.general.onepassword', 'chromeboxes')  | password_hash('sha512') }}"
  - name: apt update
    ansible.builtin.apt:
      update_cache: true
      upgrade: true
  - name: check for reboot
    register: reboot_required_file
    ansible.builtin.stat:
      path: /var/run/reboot-required
      get_checksum: false
  - name: auto remove
    ansible.builtin.apt:
      autoremove: true
  - name: reboot
    ansible.builtin.reboot:
      connect_timeout: 5
      reboot_timeout: 100
      post_reboot_delay: 30
      test_command: uptime


