---
- name: Cluster prep
  hosts: k3s_cluster
  gather_facts: true
  become: true
  roles:
    - role: k3s_prereq

- name: Setup K3S server
  hosts: server
  become: true
  vars_files: 
    /Users/ericbranson/Documents/Cluster/vault_vars.yaml
  roles:
    - role: k3s_server

- name: Setup K3S agent
  hosts: agent
  become: true
  vars_files: 
    /Users/ericbranson/Documents/Cluster/vault_vars.yaml
  roles:
    - role: k3s_agent
