- name: Clone wiringPi
  ansible.builtin.git:
    repo: https://github.com/WiringPi/WiringPi.git
    clone: true
    dest: /home/branson/wiringPi
- name: Build wiringPi
  ansible.builtin.command:
    cmd: ./build debian
    chdir: /home/branson/wiringPi
  register: wiringPi_build_result
- name: Install wiring pi
  ansible.builtin.apt:
    deb: /home/branson/wiringPi/debian-template/wiringpi_3.1_arm64.deb