- name: Reboot if required
  block:
  - name: Check if reboot required
    ansible.builtin.stat:
      path: /var/run/reboot-required
    register: reboot_required_file
  - name: Reboot if required
    ansible.builtin.reboot:
      connect_timeout: 5
      reboot_timeout: 10
      post_reboot_delay: 30
      test_command: uptime
    when: reboot_required_file.stat.exists == true